name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Build project
        run: npm run build
        
      - name: Create Wrangler config
        run: |
          echo "Creating Wrangler config file..."
          cat > wrangler.toml << EOF
          account_id = "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          EOF
          
      - name: Install Wrangler
        run: npm install -g wrangler
      
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "Deploying to Cloudflare Pages with API token..."
          wrangler pages publish dist --project-name=mateusmg